// DO NOT EDIT: Client was autogenerated from 'example.proto'
package exampleproto

import (
	"context"
	"encoding/json"

	awsreq "github.com/aws/aws-sdk-go/aws/request"
	invoker "github.com/edstell/lambda-invoker"
	"google.golang.org/protobuf/encoding/protojson"
)

type Client interface {
	Do(context.Context, *DoRequest, ...awsreq.Option) (*DoResponse, error)
}

type client struct {
	do *invoker.Invoker
}

func NewClient(i invoker.LambdaInvoker, arn string, unmarshaler func(json.RawMessage) error) Client {
	return &client{
		do: invoker.New(i, arn, invoker.AsProcedure("Do", unmarshaler)),
	}
}

func (c *client) Do(ctx context.Context, req *DoRequest, opts ...awsreq.Option) (*DoResponse, error) {
	payload, err := protojson.Marshal(req)
	if err != nil {
		return nil, err
	}
	rsp, err := c.do.Invoke(ctx, payload, opts...)
	if err != nil {
		return nil, err
	}
	out := &DoResponse{}
	if err := protojson.Unmarshal(rsp, out); err != nil {
		return nil, err
	}
	return out, nil
}
